version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      assignees:
        - "kajyr"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
     assignees:
      - 'kajyr'
